from enum import Enum


class SimCardsCompType(Enum):
    Nothing = "Nothing"
    Pair = "Pair"
    ThreeCardsFlush = "ThreeCardsFlush"
    ThreeCardsPairInFlush = "ThreeCardsPairInFlush"
    ThreeCardsStraight = "ThreeCardsStraight"
    FourCardsFlush = "FourCardsFlush"
    FourCardStraight = "FourCardStraight"
    FiveCardsStraight = "FiveCardsStraight"
    FiveCardsFlush = "FiveCardsFlush"
    FourCardsPairInFlush = "FourCardsPairInFlush"
    FourCardsTwoPairsInFlush = "FourCardsTwoPairsInFlush"
    ThreeOfKind = "ThreeOfKind"
    FiveCardsPairInFlush = "FiveCardsPairInFlush"
    FiveCardsTwoPairsInFlush = "FiveCardsTwoPairsInFlush"
    ThreeCardsFlushStraight = "ThreeCardsFlushStraight"
    FourCardsFlushStraight = "FourCardsFlushStraight"
    FourOfKind = "FourOfKind"
    FiveCardsFlushStraight = "FiveCardsFlushStraight"
    SixCardsFlush = "SixCardsFlush"
    SixCardsStraight = "SixCardsStraight"
    SixCardsPairInFlush = "SixCardsPairInFlush"
    SixCardsTwoPairsInFlush = "SixCardsTwoPairsInFlush"
    SixCardsFlushStraight = "SixCardsFlushStraight"
    SixCardsThreePairsInFlush = "SixCardsThreePairsInFlush"
    SevenCardsFlush = "SevenCardsFlush"
    SevenCardsStraight = "SevenCardsStraight"
    SevenCardsPairInFlush = "SevenCardsPairInFlush"
    SevenCardsTwoPairsInFlush = "SevenCardsTwoPairsInFlush"
    SevenCardsThreePairsInFlush = "SevenCardsThreePairsInFlush"
    SevenCardsFlushStraight = "SevenCardsFlushStraight"
    EightCardsFlush = "EightCardsFlush"
    EightCardsPairInFlush = "EightCardsPairInFlush"
    EightCardsTwoPairsInFlush = "EightCardsTwoPairsInFlush"
    EightCardsStraight = "EightCardsStraight"
    FiveOfKind = "FiveOfKind"
    EightCardsFlushStraight = "EightCardsFlushStraight"
    EightCardsThreePairsInFlush = "EightCardsThreePairsInFlush"
    EightCardsFourPairsInFlush = "EightCardsFourPairsInFlush"
    SixOfKind = "SixOfKind"
    SevenOfKind = "SevenOfKind"
    EightOfKind = "EightOfKind"
    NineCardsFlush = "NineCardsFlush"
    NineCardsStraight = "NineCardsStraight"
    NineCardsFlushStraight = "NineCardsFlushStraight"
    NineOfKind = "NineOfKind"
    TenCardsFlush = "TenCardsFlush"
    TenCardsStraight = "TenCardsStraight"
    TenCardsFlushStraight = "TenCardsFlushStraight"
    TenOfKind = "TenOfKind"
    None_ = "None"

    def __str__(self):
        if self == SimCardsCompType.None_:
            return "None"
        return self.value


class SimCardOverAllHandRank(Enum):
    None_ = "None"
    Nothing = "Nothing"
    Pair = "Pair"
    TwoPairs = "TwoPairs"
    ThreeOfKind = "ThreeOfKind"
    ThreeCardsFlushStraight = "ThreeCardsFlushStraight"
    FiveCardsStraight = "FiveCardsStraight"
    FiveCardsFlush = "FiveCardsFlush"
    FullHouse = "FullHouse"
    Mansion = "Mansion"
    SixCardsStraight = "SixCardsStraight"
    SixCardsFlush = "SixCardsFlush"
    SevenCardsStraight = "SevenCardsStraight"
    FourCardsFlushStraight = "FourCardsFlushStraight"
    FourOfKind = "FourOfKind"
    FiveCardsFlushStraight = "FiveCardsFlushStraight"
    EightCardsStraight = "EightCardsStraight"
    SevenCardsFlush = "SevenCardsFlush"
    NineCardsStraight = "NineCardsStraight"
    SixCardsFlushStraight = "SixCardsFlushStraight"
    EightCardsFlush = "EightCardsFlush"
    SevenCardsFlushStraight = "SevenCardsFlushStraight"
    EightCardsFlushStraight = "EightCardsFlushStraight"
    NineCardsFlush = "NineCardsFlush"
    NineCardsFlushStraight = "NineCardsFlushStraight"

    def __str__(self):
        if self == SimCardOverAllHandRank.None_:
            return "None"
        return self.value


class SimCardsBattleHandRank(Enum):
    Nothing = "Nothing"
    Pair = "Pair"
    TwoPairs = "TwoPairs"
    ThreeCardsFlush = "ThreeCardsFlush"
    ThreeCardsStraight = "ThreeCardsStraight"
    ThreeCardsFlushStraight = "ThreeCardsFlushStraight"
    ThreeOfKind = "ThreeOfKind"
    FourCardsFlush = "FourCardsFlush"
    FourCardStraight = "FourCardStraight"
    FourCardsFlushStraight = "FourCardsFlushStraight"
    FiveCardsStraight = "FiveCardsStraight"
    FiveCardsFlush = "FiveCardsFlush"
    FiveCardsFlushStraight = "FiveCardsFlushStraight"
    SixCardsStraight = "SixCardsStraight"
    SixCardsFlush = "SixCardsFlush"
    SixCardsFlushStraight = "SixCardsFlushStraight"
    SevenCardsStraight = "SevenCardsStraight"
    SevenCardsFlush = "SevenCardsFlush"
    SevenCardsFlushStraight = "SevenCardsFlushStraight"
    EightCardsStraight = "EightCardsStraight"
    EightCardsFlush = "EightCardsFlush"
    EightCardsFlushStraight = "EightCardsFlushStraight"
    NineCardsStraight = "NineCardsStraight"
    NineCardsFlush = "NineCardsFlush"
    NineCardsFlushStraight = "NineCardsFlushStraight"
    TenCardsStraight = "TenCardsStraight"
    TenCardsFlush = "TenCardsFlush"
    TenCardsFlushStraight = "TenCardsFlushStraight"
    FourOfKind = "FourOfKind"
    FiveOfKind = "FiveOfKind"
    SixOfKind = "SixOfKind"
    SevenOfKind = "SevenOfKind"
    EightOfKind = "EightOfKind"
    NineOfKind = "NineOfKind"
    TenOfKind = "TenOfKind"
    FullHouse = "FullHouse"
    TownHouse = "TownHouse"
    Mansion = "Mansion"
    FourCardsTwoPairsInFlush = "FourCardsTwoPairsInFlush"
    FiveCardsTwoPairsInFlush = "FiveCardsTwoPairsInFlush"
    SixCardsTwoPairsInFlush = "SixCardsTwoPairsInFlush"
    SevenCardsTwoPairsInFlush = "SevenCardsTwoPairsInFlush"
    EightCardsTwoPairsInFlush = "EightCardsTwoPairsInFlush"
    SixCardsThreePairsInFlush = "SixCardsThreePairsInFlush"
    SevenCardsThreePairsInFlush = "SevenCardsThreePairsInFlush"
    EightCardsThreePairsInFlush = "EightCardsThreePairsInFlush"
    EightCardsFourPairsInFlush = "EightCardsFourPairsInFlush"
    ThreeCardsPairInFlush = "ThreeCardsPairInFlush"
    FourCardsPairInFlush = "FourCardsPairInFlush"
    FiveCardsPairInFlush = "FiveCardsPairInFlush"
    SixCardsPairInFlush = "SixCardsPairInFlush"
    SevenCardsPairInFlush = "SevenCardsPairInFlush"
    EightCardsPairInFlush = "EightCardsPairInFlush"
