
namespace GenericPoker
{
	/*
	public enum PokerBitTypes
	{
		BitPair = 0b_0000_0001,
		BitTwoPair = 0b_0000_0010,
		BitThreeOfKind = 0b_0000_0100,
		BitStraight = 0b_0000_1000,
		BitFlush = 0b_0001_0000,
		BitFourOfKind = 0b_0010_0000,
		BitFiveOfKind = 0b_0100_0000
	}*/

	public enum EightCardsPokerRank
	{
		OnePair,
		TwoPairs,
		ThreeCardsFlush,
		ThreeCardsStraight,
		ThreeCardsFlushStraight,
		ThreeOfKind,
		PairThreeCardsFlush,
		PairThreeCardsStraight,
		PairThreeCardsFlushStraight,
		FourCardsFlush,
		FourCardsStraight,
		FourCardsFlushStraight,
		FiveCardsStraight,
		FiveCardsFlush,
		FullHouse,
		FiveOfKind,
		SixCardsStraight,
		SixCardsFlush,
		SixCardsFlushStraight,
		SevenCardsStraight,
		SevenCardsFlush,
		SevenCardsFlushStraight,
		EightCardsStraight,
		EightCardsFlush,
		EightCardsFlushStraight,
	}

	public enum BaseCompType
	{
		Nothing,
		Pair,
		ThreeCardsFlush,
		ThreeCardsPairInFlush,
		ThreeCardsStraight,
		FourCardsFlush,
		FourCardStraight,
		FiveCardsStraight,
		FiveCardsFlush,
		FourCardsPairInFlush,
		FourCardsTwoPairsInFlush,
		ThreeOfKind,
		FiveCardsPairInFlush,
		FiveCardsTwoPairsInFlush,
		ThreeCardsFlushStraight,
		FourCardsFlushStraight,
		FourOfKind,
		FiveCardsFlushStraight,
		SixCardsFlush,
		SixCardsStraight,
		SixCardsPairInFlush,
		SixCardsTwoPairsInFlush,
		SixCardsFlushStraight,
		SixCardsThreePairsInFlush,
		SevenCardsFlush,
		SevenCardsStraight,
		SevenCardsPairInFlush,
		SevenCardsTwoPairsInFlush,
		SevenCardsThreePairsInFlush,
		SevenCardsFlushStraight,
		EightCardsFlush,
		EightCardsPairInFlush,
		EightCardsTwoPairsInFlush,
		EightCardsStraight,
		FiveOfKind,
		EightCardsFlushStraight,
		EightCardsThreePairsInFlush,
		EightCardsFourPairsInFlush,
		SixOfKind,
		SevenOfKind,
		EightOfKind,
		NineCardsFlush,
		NineCardsStraight,
		NineCardsFlushStraight,
		NineOfKind,
		TenCardsFlush,
		TenCardsStraight,
		TenCardsFlushStraight,
		TenOfKind,
		None,
	}
	
	/*
	public enum EightCardQualifiedExceptionalBackHand
	{
		Nothing,
		EightCardsFourPairsInFlush,
		EightCardsFlushStraight,
		SevenOfKind,
		EightCardsThreePairsInFlush,
		SevenCardsFlushStraight,
		EightCardsFlush,
		SixOfKind,
		EightCardsTwoPairsInFlush,
		SevenCardsThreePairsInFlush,
		EightCardsPairInFlush,
		SixCardsThreePairsInFlush,
		SixCardsFlushStraight,
		SevenCardsTwoPairsInFlush,
		SevenCardsFlush,
		FiveOfKind,
		EightCardsStraight,
		SevenCardsPairInFlush,
		FiveCardsFlushStraight,
		SixCardsTwoPairsInFlush,
		FiveCardsTwoPairsInFlush,
		FourCardsTwoPairsInFlush,
		SevenCardsStraight,
		SixCardsPairInFlush,
		SixCardsFlush,
		FourCardsFlushStraight,
		FourOfKind,
		SixCardsStraight,
		FiveCardsPairInFlush,
		ThreeCardsFlushStraightAndPair,
		FiveCardsFlush,
		ThreeCardsFlushStraight,
		ThreeOfKindAndPair,
		FiveCardsStraight,
		FourCardsPairInFlush,
		ThreeCardsPairInFlushAndPair,
		ThreeOfKind,
		ThreeCardsPairInFlush,
		FourCardsFlush,
		FourCardStraight,
		TwoPairs,
		Pair,
	}
	*/

	public enum PokerRankTypes
	{
		FiveOfKind = 500,
		RoyalFlushStraight = 300,
		FlushStraight = 200,
		FourOfKind = 150,
		FullHouse = 80,
		Flush = 40,
		Straight = 30,
		FourCardsFlushStraight = 25,
		ThreeOfKind = 20,
		TwoPairs = 15,
		ThreeCardsFlushStraight = 12,
		FourCardsFlush = 10,
		FourCardStraight = 8,
		OnePair = 5,
		Nothing = 0
	}

	public enum CompType
	{
		Kind,
		Flush,
		Straight,
		FullHouse,
		FlushStraight,
	}
	
	public enum PokerOverAllHandRank
    {
        None,
        Nothing,
        Pair,
        TwoPairs,
        ThreeOfKind,
        ThreeCardsFlushStraight,
        FiveCardsStraight,
        FiveCardsFlush,
        FullHouse,
        Mansion,
        SixCardsStraight,
        SixCardsFlush,
        SevenCardsStraight,
        FourCardsFlushStraight,
        FourOfKind,
        FiveCardsFlushStraight,
        EightCardsStraight,
        SevenCardsFlush,
        NineCardsStraight,
        SixCardsFlushStraight,
        EightCardsFlush,
        SevenCardsFlushStraight,
        EightCardsFlushStraight,
        NineCardsFlush,
        NineCardsFlushStraight
    }

    public enum PokerBattleHandRank
    {
        Nothing,
        Pair,
        TwoPairs,
        ThreeCardsFlush,
        ThreeCardsStraight,
        ThreeCardsFlushStraight,
        ThreeOfKind,
        FourCardsFlush,
        FourCardStraight,
        FourCardsFlushStraight,
        FiveCardsStraight,
        FiveCardsFlush,
        FiveCardsFlushStraight,
        SixCardsStraight,
        SixCardsFlush,
        SixCardsFlushStraight,
        SevenCardsStraight,
        SevenCardsFlush,
        SevenCardsFlushStraight,
        EightCardsStraight,
        EightCardsFlush,
        EightCardsFlushStraight,
        NineCardsStraight,
        NineCardsFlush,
        NineCardsFlushStraight,
        TenCardsStraight,
        TenCardsFlush,
        TenCardsFlushStraight,
        FourOfKind,
        FiveOfKind,
        SixOfKind,
        SevenOfKind,
        EightOfKind,
        NineOfKind,
        TenOfKind,
        FullHouse,
        TownHouse,
        Mansion,
        FourCardsTwoPairsInFlush,
        FiveCardsTwoPairsInFlush,
        SixCardsTwoPairsInFlush,
        SevenCardsTwoPairsInFlush,
        EightCardsTwoPairsInFlush,
        SixCardsThreePairsInFlush,
        SevenCardsThreePairsInFlush,
        EightCardsThreePairsInFlush,
        EightCardsFourPairsInFlush,
        ThreeCardsPairInFlush,
        FourCardsPairInFlush,
        FiveCardsPairInFlush,
        SixCardsPairInFlush,
        SevenCardsPairInFlush,
        EightCardsPairInFlush,
    }

	public enum PokerCardCompRank
	{
		ThreeCardFlush,
		ThreeCardStraight,
		FourCardFlush,
		FourCardStraight,
		ThreeOfKind,
		ThreeCardFlushStraight,
		FiveCardStraight,
		FiveCardFlush,
		FullHouse,
		FourOfKind,
		FourCardFlushStraight,
		FiveCardFlushStraight,
		FiveOfKind,

		// Following, the associated hasn't precisely calculated, and just use temporarily values  
		SixCardStraight,
		SixCardFlush,
		SixCardFlushStraight,
		SevenCardStraight,
		SevenCardFlush,
		SevenCardFlushStraight,
		EightCardStraight,
		EightCardFlush,
		EightCardFlushStraight,
		SixOfKind,
		SevenOfKind,
		EightOfKind,
		NineCardStraight,
		NineCardFlush,
		NineCardFlushStraight,
		TenCardStraight,
		TenCardFlush,
		TenCardFlushStraight,
		ElevenCardStraight,
		ElevenCardFlush,
		ElevenFlushStraight,
		TwelveCardStraight,
		TwelveCardFlush,
		TwelveFlushStraight,
		ThirteenCardStraight,
		ThirteenCardFlush,
		ThirteenCardFlushStraight,
		FourteenCardStraight,
	}
		
}

