
namespace GenericPoker
{
	public enum PokerBitTypes
	{
		BitPair = 0b_0000_0001,
		BitTwoPair = 0b_0000_0010,
		BitThreeOfKind = 0b_0000_0100,
		BitStraight = 0b_0000_1000,
		BitFlush = 0b_0001_0000,
		BitFourOfKind = 0b_0010_0000,
		BitFiveOfKind = 0b_0100_0000
	}

	public enum EightCardsPokerRank
	{
		OnePair,
		TwoPairs,
		ThreeCardsFlush,
		ThreeCardsStraight,
		ThreeCardsFlushStraight,
		ThreeOfKind,
		PairThreeCardsFlush,
		PairThreeCardsStraight,
		PairThreeCardsFlushStraight,
		FourCardsFlush,
		FourCardsStraight,
		FourCardsFlushStraight,
		FiveCardsStraight,
		FiveCardsFlush,
		FullHouse,
		FiveOfKind,
		SixCardsStraight,
		SixCardsFlush,
		SixCardsFlushStraight,
		SevenCardsStraight,
		SevenCardsFlush,
		SevenCardsFlushStraight,
		EightCardsStraight,
		EightCardsFlush,
		EightCardsFlushStraight,
	}


	public enum EightCardsComboType_old
	{
		OnePair,
		TwoPairs,
		ThreePairs,
		FourPairs,
		ThreeOfKind,
		TwoThreeOfKinds,
		OnePairAndThreeOfKind,
		TwoPairsAndThreeOfKind,
		OnePairAndTwoThreeOfKinds,
		FourOfKind,
		OnePairAndFourOfKind,
		TwoPairsAndFourOfKind,
		ThreeOfKindAndFourOfKind,
		TwoFourOfKinds,

		ThreeCardFlush,
		ThreeCardStraight,
		ThreeCardFlushStraight,
		TwoThreeCardFlushes,
		TwoThreeCardStraights,
		TwoThreeCardFlushStraights,
	}

	public enum EightCardsComboType_Old_With_3_flush_straight
	{
		Pair,
		ThreeOfKind,
		FourOfKind,
		ThreeCardsFlush,
		ThreeCardStraight,
		ThreeCardsFlushStraight,
		FourCardsFlush,
		FourCardStraight,
		FourCardsFlushStraight,
		FiveCardsFlush,
		FiveCardsStraight,
		FiveCardsFlushStraight,
		SixCardsFlush,
		SixCardsStraight,
		SixCardsFlushStraight,
		SevenCardsFlush,
		SevenCardsStraight,
		SevenCardsFlushStraight,
		EightCardsFlush,
		EightCardsStraight,
		EightCardsFlushStraight,
	}


	public enum EightCardsCompType
	{
		Pair,
		ThreeCardsFlush,
		ThreeCardsPairInFlush,
		ThreeCardsStraight,
		FourCardsFlush,
		FourCardStraight,
		FiveCardsStraight,
		FiveCardsFlush,
		FourCardsPairInFlush, //
		FourCardsTwoPairsInFlush, //
		ThreeOfKind,
		FiveCardsPairInFlush,
		FiveCardsTwoPairsInFlush,
		ThreeCardsFlushStraight,
		FourCardsFlushStraight,
		FourOfKind,
		FiveCardsFlushStraight,
		SixCardsFlush,
		SixCardsStraight,
		SixCardsPairInFlush,
		SixCardsTwoPairsInFlush,
		SixCardsFlushStraight,
		SixCardsThreePairsInFlush,
		SevenCardsFlush,
		SevenCardsStraight,
		SevenCardsPairInFlush,
		SevenCardsTwoPairsInFlush,
		SevenCardsThreePairsInFlush,
		SevenCardsFlushStraight,
		EightCardsFlush,
		EightCardsPairInFlush,
		EightCardsTwoPairsInFlush,
		EightCardsStraight,
		FiveOfKind,
		EightCardsFlushStraight,
		EightCardsThreePairsInFlush,
		EightCardsFourPairsInFlush,
		SixOfKind,
		SevenOfKind,
		EightOfKind,
		None,
	}
	
	/*
	public enum EightCardsBackHandRank
	{
		EightCardsFourPairsInFlush,
		EightCardsFlushStraight,
		SevenOfKind,
		EightCardsThreePairsInFlush,
		SevenCardsFlushStraight,
		EightCardsFlush,
		SixOfKind,
		EightCardsTwoPairsInFlush,
		SevenCardsThreePairsInFlush,
		EightCardsPairInFlush,
		SixCardsThreePairsInFlush,
		SixCardsFlushStraight,
		SevenCardsTwoPairsInFlush,
		SevenCardsFlush,
		FiveOfKind,
		EightCardsStraight,
		SevenCardsPairInFlush,
		FiveCardsFlushStraight,
		SixCardsTwoPairsInFlush,
		FiveCardsTwoPairsInFlush,
		FourCardsTwoPairsInFlush,
		SevenCardsStraight,
		SixCardsPairInFlush,
		SixCardsFlush,
		FourCardsFlushStraight,
		FourOfKind,
		SixCardsStraight,
		FiveCardsPairInFlush,
		ThreeCardsFlushStraightAndPair,
		FiveCardsFlush,
		ThreeCardsFlushStraight,
		ThreeOfKindAndPair,
		FiveCardsStraight,
		FourCardsPairInFlush,
		ThreeCardsPairInFlushAndPair,
		ThreeOfKind,
		ThreeCardsPairInFlush,
		FourCardsFlush,
		FourCardStraight,
		TwoPairs,
		Pair,
	}
	*/

	public enum EightCardQualifiedExceptionalBackHand
	{
		EightCardsFourPairsInFlush,
		EightCardsFlushStraight,
		SevenOfKind,
		EightCardsThreePairsInFlush,
		SevenCardsFlushStraight,
		EightCardsFlush,
		SixOfKind,
		EightCardsTwoPairsInFlush,
		SevenCardsThreePairsInFlush,
		EightCardsPairInFlush,
		SixCardsThreePairsInFlush,
		SixCardsFlushStraight,
		SevenCardsTwoPairsInFlush,
		SevenCardsFlush,
		FiveOfKind,
		EightCardsStraight,
		SevenCardsPairInFlush,
		FiveCardsFlushStraight,
		SixCardsTwoPairsInFlush,
		FiveCardsTwoPairsInFlush,
		FourCardsTwoPairsInFlush,
		SevenCardsStraight,
		SixCardsPairInFlush,
		SixCardsFlush,
		FourCardsFlushStraight,
		FourOfKind,
		SixCardsStraight,
		FiveCardsPairInFlush,
		ThreeCardsFlushStraightAndPair,
		FiveCardsFlush,
		ThreeCardsFlushStraight,
		ThreeOfKindAndPair,
		FiveCardsStraight,
		FourCardsPairInFlush,
		ThreeCardsPairInFlushAndPair,
		ThreeOfKind,
		ThreeCardsPairInFlush,
		FourCardsFlush,
		FourCardStraight,
		TwoPairs,
		Pair,
	}
	

public enum PokerRankTypes
	{
		FiveOfKind = 500,
		RoyalFlushStraight = 300,
		FlushStraight = 200,
		FourOfKind = 150,
		FullHouse = 80,
		Flush = 40,
		Straight = 30,
		FourCardsFlushStraight = 25,
		ThreeOfKind = 20,
		TwoPairs = 15,
		ThreeCardsFlushStraight = 12,
		FourCardsFlush = 10,
		FourCardStraight = 8,
		OnePair = 5,
		Nothing = 0
	}

	public enum CompType
	{
		Kind,
		Flush,
		Straight,
		FullHouse,
		FlushStraight,
	}

	public enum PokerCardCompRank
	{
		ThreeCardFlush = 19,
		ThreeCardStraight = 29,
		FourCardFlush = 95,
		FourCardStraight = 96,
		ThreeOfKind = 425,
		ThreeCardFlushStraight = 460,
		FiveCardStraight = 254,
		FiveCardFlush = 505,
		FullHouse = 694,
		FourOfKind = 4165,
		FourCardFlushStraight = 6153,
		FiveCardFlushStraight = 64974,
		FiveOfKind = 100000,

		// Following, the associated hasn't precisely calculated, and just use temporarily values  
		SixCardStraight = 100000,
		SixCardFlush = 100000,
		SixCardFlushStraight = 100000,
		SevenCardStraight = 100000,
		SevenCardFlush = 100000,
		SevenCardFlushStraight = 100000,
		EightCardStraight = 100000,
		EightCardFlush = 100000,
		EightCardFlushStraight = 100000,
		SixOfKind = 200000,
		SevenOfKind = 300000,
		EightOfKind = 400000,
		NineCardStraight = 100000,
		NineCardFlush = 100000,
		NineCardFlushStraight = 100000,
		TenCardStraight = 100000,
		TenCardFlush = 100000,
		TenCardFlushStraight = 100000,
		ElevenCardStraight = 100000,
		ElevenCardFlush = 100000,
		ElevenFlushStraight = 100000,
		TwelveCardStraight = 100000,
		TwelveCardFlush = 100000,
		TwelveFlushStraight = 100000,
		ThirteenCardStraight = 100000,
		ThirteenCardFlush = 100000,
		ThirteenCardFlushStraight = 100000,
		FourteenCardStraight = 100000,
	}
		
}